/**
 * IOPHIN - Poverty Hotspot Identifier System (PHIS)
 * Backend API Server - "The Chassis"
 * 
 * This Express.js server provides RESTful endpoints to serve geospatial
 * poverty data generated by the Machine Learning engine.
 */

import express from 'express';
import cors from 'cors';
import compression from 'compression';
import dotenv from 'dotenv';
import { createReadStream, existsSync } from 'fs';
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

// Load environment variables
dotenv.config();

// Get current directory (ES module workaround)
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Configuration
const PORT = process.env.PORT || 5000;
const DATA_PATH = join(__dirname, process.env.DATA_PATH || '../data/processed/hotspots.geojson');

// Initialize Express app
const app = express();

// Middleware
app.use(cors({
  origin: process.env.NODE_ENV === 'production' 
    ? process.env.CLIENT_URL 
    : ['http://localhost:5173', 'http://localhost:3000'],
  credentials: true
}));

app.use(compression()); // Enable GZIP compression for large GeoJSON files
app.use(express.json());

/**
 * Health check endpoint
 */
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'healthy', 
    timestamp: new Date().toISOString(),
    environment: process.env.NODE_ENV || 'development'
  });
});

/**
 * GET /api/hotspots
 * Streams the GeoJSON hotspots data to the client
 * 
 * Features:
 * - GZIP compression enabled via compression middleware
 * - Efficient streaming for large files
 * - User-friendly error handling
 */
app.get('/api/hotspots', async (req, res) => {
  try {
    // Check if file exists
    if (!existsSync(DATA_PATH)) {
      console.error(`GeoJSON file not found at: ${DATA_PATH}`);
      return res.status(503).json({
        error: 'Service Unavailable',
        message: 'Model is currently retraining. Please try again in a few moments.',
        timestamp: new Date().toISOString()
      });
    }

    // Set appropriate headers
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', 'public, max-age=3600'); // Cache for 1 hour

    // Stream the file to client (memory-efficient for large files)
    const fileStream = createReadStream(DATA_PATH, { encoding: 'utf8' });
    
    fileStream.on('error', (error) => {
      console.error('Error streaming GeoJSON:', error);
      if (!res.headersSent) {
        res.status(500).json({
          error: 'Internal Server Error',
          message: 'Failed to load hotspots data'
        });
      }
    });

    fileStream.pipe(res);
    
  } catch (error) {
    console.error('Error in /api/hotspots:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'An unexpected error occurred'
    });
  }
});

/**
 * GET /api/stats
 * Calculates and returns summary statistics from the hotspots data
 * 
 * Returns:
 * - Total number of LGAs monitored
 * - Count of each risk level (High, Medium, Low, Minimal)
 * - Average MPI score
 * - Average nightlight intensity
 */
app.get('/api/stats', async (req, res) => {
  try {
    // Check if file exists
    if (!existsSync(DATA_PATH)) {
      return res.status(503).json({
        error: 'Service Unavailable',
        message: 'Model is currently retraining. Please try again in a few moments.'
      });
    }

    // Read and parse GeoJSON file
    const data = await readFile(DATA_PATH, 'utf8');
    const geoJSON = JSON.parse(data);
    const features = geoJSON.features || [];

    // Calculate statistics
    const stats = {
      totalLGAs: features.length,
      riskDistribution: {
        high: 0,
        medium: 0,
        low: 0,
        minimal: 0
      },
      averageMPI: 0,
      averageNightlight: 0,
      states: new Set(),
      timestamp: new Date().toISOString()
    };

    let totalMPI = 0;
    let totalNightlight = 0;

    features.forEach(feature => {
      const { risk_level, MPI, mean_nightlight_intensity, State } = feature.properties;
      
      // Count risk levels
      if (risk_level === 'High') stats.riskDistribution.high++;
      else if (risk_level === 'Medium') stats.riskDistribution.medium++;
      else if (risk_level === 'Low') stats.riskDistribution.low++;
      else if (risk_level === 'Minimal') stats.riskDistribution.minimal++;

      // Accumulate for averages
      if (MPI) totalMPI += MPI;
      if (mean_nightlight_intensity) totalNightlight += mean_nightlight_intensity;
      
      // Track unique states
      if (State) stats.states.add(State);
    });

    // Calculate averages
    stats.averageMPI = features.length > 0 ? (totalMPI / features.length).toFixed(4) : 0;
    stats.averageNightlight = features.length > 0 ? (totalNightlight / features.length).toFixed(2) : 0;
    stats.statesCount = stats.states.size;
    delete stats.states; // Remove Set from response

    res.json(stats);

  } catch (error) {
    console.error('Error in /api/stats:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to calculate statistics'
    });
  }
});

/**
 * GET /api/lga/:name
 * Get detailed information for a specific LGA
 */
app.get('/api/lga/:name', async (req, res) => {
  try {
    const lgaName = decodeURIComponent(req.params.name);

    if (!existsSync(DATA_PATH)) {
      return res.status(503).json({
        error: 'Service Unavailable',
        message: 'Data not available'
      });
    }

    const data = await readFile(DATA_PATH, 'utf8');
    const geoJSON = JSON.parse(data);
    const feature = geoJSON.features.find(
      f => f.properties.LGA_Name === lgaName
    );

    if (!feature) {
      return res.status(404).json({
        error: 'Not Found',
        message: `LGA '${lgaName}' not found`
      });
    }

    res.json(feature);

  } catch (error) {
    console.error('Error in /api/lga/:name:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to fetch LGA data'
    });
  }
});

/**
 * 404 handler for undefined routes
 */
app.use((req, res) => {
  res.status(404).json({
    error: 'Not Found',
    message: `Route ${req.method} ${req.path} does not exist`,
    availableEndpoints: [
      'GET /api/health',
      'GET /api/hotspots',
      'GET /api/stats',
      'GET /api/lga/:name'
    ]
  });
});

/**
 * Global error handler
 */
app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(500).json({
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : 'An unexpected error occurred'
  });
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 IOPHIN API Server running on port ${PORT}`);
  console.log(`📊 Data path: ${DATA_PATH}`);
  console.log(`🌍 Environment: ${process.env.NODE_ENV || 'development'}`);
  console.log(`✅ GZIP compression: enabled`);
  console.log(`\n📍 Available endpoints:`);
  console.log(`   - GET http://localhost:${PORT}/api/health`);
  console.log(`   - GET http://localhost:${PORT}/api/hotspots`);
  console.log(`   - GET http://localhost:${PORT}/api/stats`);
  console.log(`   - GET http://localhost:${PORT}/api/lga/:name`);
});

export default app;
