/**
 * IOPHIN - Poverty Hotspot Identifier System (PHIS)
 * Backend API Server - "The Chassis"
 * 
 * This Express.js server provides RESTful endpoints to serve geospatial
 * poverty data generated by the Machine Learning engine.
 */

import express from 'express';
import cors from 'cors';
import compression from 'compression';
import dotenv from 'dotenv';
import rateLimit from 'express-rate-limit';
import { createReadStream, existsSync } from 'fs';
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import * as db from './database.js';

// Load environment variables
dotenv.config();

// Get current directory (ES module workaround)
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Configuration
const PORT = process.env.PORT || 5000;
const DATA_PATH = join(__dirname, process.env.DATA_PATH || '../data/processed/hotspots.geojson');
const USE_DATABASE = (process.env.USE_DATABASE ?? 'true') === 'true'; // Default to true for dynamic mode

// Cache for GeoJSON data and stats
let cachedGeoJSON = null;
let cachedStats = null;
let lgaIndex = new Map();
let cacheTimestamp = null;

/**
 * Load and cache GeoJSON data
 */
async function loadGeoJSONData() {
  try {
    const { stat } = await import('fs/promises');
    const fileStat = await stat(DATA_PATH);
    const fileModTime = fileStat.mtime.getTime();
    
    // Check if cache is still valid
    if (cachedGeoJSON && cacheTimestamp === fileModTime) {
      return cachedGeoJSON;
    }
    
    // Read and parse file
    const data = await readFile(DATA_PATH, 'utf8');
    const geoJSON = JSON.parse(data);
    
    // Update cache
    cachedGeoJSON = geoJSON;
    cacheTimestamp = fileModTime;
    
    // Build LGA index
    lgaIndex.clear();
    if (geoJSON.features) {
      geoJSON.features.forEach((feature, index) => {
        if (feature.properties && feature.properties.LGA_Name) {
          lgaIndex.set(feature.properties.LGA_Name, index);
        }
      });
    }
    
    // Invalidate stats cache when data changes
    cachedStats = null;
    
    return geoJSON;
  } catch (error) {
    console.error('Error loading GeoJSON:', error);
    throw error;
  }
}

/**
 * Calculate and cache statistics
 */
async function calculateStats() {
  // Return cached stats if available
  if (cachedStats) {
    return cachedStats;
  }
  
  const geoJSON = await loadGeoJSONData();
  const features = geoJSON.features || [];
  
  const stats = {
    totalLGAs: features.length,
    riskDistribution: {
      high: 0,
      medium: 0,
      low: 0,
      minimal: 0
    },
    averageMPI: 0,
    averageNightlight: 0,
    states: new Set(),
    timestamp: new Date().toISOString()
  };
  
  let totalMPI = 0;
  let mpiCount = 0;
  let totalNightlight = 0;
  let nightlightCount = 0;
  
  features.forEach(feature => {
    const { risk_level, MPI, mean_nightlight_intensity, State } = feature.properties;
    
    // Count risk levels
    if (risk_level === 'High') stats.riskDistribution.high++;
    else if (risk_level === 'Medium') stats.riskDistribution.medium++;
    else if (risk_level === 'Low') stats.riskDistribution.low++;
    else if (risk_level === 'Minimal') stats.riskDistribution.minimal++;
    
    // Accumulate for averages (check for numeric values, including 0)
    if (typeof MPI === 'number') {
      totalMPI += MPI;
      mpiCount++;
    }
    if (typeof mean_nightlight_intensity === 'number') {
      totalNightlight += mean_nightlight_intensity;
      nightlightCount++;
    }
    
    // Track unique states
    if (State) stats.states.add(State);
  });
  
  // Calculate averages using actual counts
  stats.averageMPI = mpiCount > 0 ? (totalMPI / mpiCount).toFixed(4) : '0';
  stats.averageNightlight = nightlightCount > 0 ? (totalNightlight / nightlightCount).toFixed(2) : '0';
  stats.statesCount = stats.states.size;
  delete stats.states; // Remove Set from response
  
  // Cache the results
  cachedStats = stats;
  
  return stats;
}

// Initialize Express app
const app = express();

// Rate limiting to prevent abuse
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // Limit each IP to 100 requests per windowMs
  message: 'Too many requests from this IP, please try again later.',
  standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers
});

// Apply rate limiter to all routes
app.use(limiter);

// Middleware
const isProduction = process.env.NODE_ENV === 'production';

const allowedOrigins = isProduction
  ? (() => {
      const clientUrl = process.env.CLIENT_URL;
      if (!clientUrl) {
        throw new Error('CLIENT_URL environment variable must be defined in production for CORS configuration.');
      }
      return clientUrl;
    })()
  : ['http://localhost:5173', 'http://localhost:3000'];

app.use(cors({
  origin: allowedOrigins,
  credentials: true
}));

app.use(compression()); // Enable GZIP compression for large GeoJSON files
app.use(express.json());

/**
 * Health check endpoint
 */
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'healthy', 
    timestamp: new Date().toISOString(),
    environment: process.env.NODE_ENV || 'development'
  });
});

/**
 * GET /api/hotspots
 * Returns GeoJSON hotspots data from database (dynamic) or file (static fallback)
 * 
 * Features:
 * - GZIP compression enabled via compression middleware
 * - Real-time data from database when available
 * - Fallback to static file for compatibility
 * - User-friendly error handling
 */
app.get('/api/hotspots', async (req, res) => {
  try {
    // Try database first if enabled
    if (USE_DATABASE && db.isDatabaseAvailable()) {
      console.log('📊 Serving hotspots from database (real-time data)');
      
      const geoJSON = db.getHotspotsAsGeoJSON();
      
      if (geoJSON) {
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Cache-Control', 'public, max-age=60'); // Cache for 1 minute (real-time)
        res.setHeader('X-Data-Source', 'database');
        return res.json(geoJSON);
      }
    }
    
    // Fallback to file-based approach
    console.log('📁 Serving hotspots from static file (fallback)');
    
    // Check if file exists
    if (!existsSync(DATA_PATH)) {
      console.error(`GeoJSON file not found at: ${DATA_PATH}`);
      return res.status(503).json({
        error: 'Service Unavailable',
        message: 'Model is currently retraining. Please try again in a few moments.',
        timestamp: new Date().toISOString()
      });
    }

    // Set appropriate headers
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', 'public, max-age=3600'); // Cache for 1 hour
    res.setHeader('X-Data-Source', 'file');

    // Stream the file to client (memory-efficient for large files)
    const fileStream = createReadStream(DATA_PATH, { encoding: 'utf8' });
    
    fileStream.on('error', (error) => {
      console.error('Error streaming GeoJSON:', error);
      if (!res.headersSent) {
        res.status(500).json({
          error: 'Internal Server Error',
          message: 'Failed to load hotspots data'
        });
      }
    });

    fileStream.pipe(res);
    
  } catch (error) {
    console.error('Error in /api/hotspots:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'An unexpected error occurred'
    });
  }
});

/**
 * GET /api/stats
 * Calculates and returns summary statistics from the hotspots data
 * Uses database for real-time stats or file-based cache for static mode
 * 
 * Returns:
 * - Total number of LGAs monitored
 * - Count of each risk level (High, Medium, Low, Minimal)
 * - Average MPI score
 * - Average nightlight intensity
 * - Conflict zones count (dynamic mode only)
 */
app.get('/api/stats', async (req, res) => {
  try {
    // Try database first if enabled
    if (USE_DATABASE && db.isDatabaseAvailable()) {
      console.log('📊 Serving stats from database (real-time)');
      
      const stats = db.getStatistics();
      
      if (stats) {
        res.setHeader('X-Data-Source', 'database');
        return res.json(stats);
      }
    }
    
    // Fallback to file-based approach
    console.log('📁 Serving stats from static file (fallback)');
    
    // Check if file exists
    if (!existsSync(DATA_PATH)) {
      return res.status(503).json({
        error: 'Service Unavailable',
        message: 'Model is currently retraining. Please try again in a few moments.'
      });
    }

    // Use cached stats
    const stats = await calculateStats();
    res.setHeader('X-Data-Source', 'file');
    res.json(stats);

  } catch (error) {
    console.error('Error in /api/stats:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to calculate statistics'
    });
  }
});

/**
 * GET /api/lga/:name
 * Get detailed information for a specific LGA
 * Uses database for real-time data or indexed cache for static mode
 */
app.get('/api/lga/:name', async (req, res) => {
  try {
    const lgaName = decodeURIComponent(req.params.name);

    // Try database first if enabled
    if (USE_DATABASE && db.isDatabaseAvailable()) {
      console.log(`📊 Fetching LGA '${lgaName}' from database`);
      
      const lga = db.getLGAByName(lgaName);
      
      if (lga) {
        res.setHeader('X-Data-Source', 'database');
        return res.json(lga);
      } else {
        return res.status(404).json({
          error: 'Not Found',
          message: `LGA '${lgaName}' not found`
        });
      }
    }
    
    // Fallback to file-based approach
    console.log(`📁 Fetching LGA '${lgaName}' from static file (fallback)`);

    if (!existsSync(DATA_PATH)) {
      return res.status(503).json({
        error: 'Service Unavailable',
        message: 'Data not available'
      });
    }

    // Load cached data with index
    const geoJSON = await loadGeoJSONData();
    const featureIndex = lgaIndex.get(lgaName);
    
    if (featureIndex === undefined) {
      return res.status(404).json({
        error: 'Not Found',
        message: `LGA '${lgaName}' not found`
      });
    }
    
    const feature = geoJSON.features[featureIndex];
    res.setHeader('X-Data-Source', 'file');
    res.json(feature);

  } catch (error) {
    console.error('Error in /api/lga/:name:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to fetch LGA data'
    });
  }
});

/**
 * 404 handler for undefined routes
 */
app.use((req, res) => {
  res.status(404).json({
    error: 'Not Found',
    message: `Route ${req.method} ${req.path} does not exist`,
    availableEndpoints: [
      'GET /api/health',
      'GET /api/hotspots',
      'GET /api/stats',
      'GET /api/lga/:name'
    ]
  });
});

/**
 * Global error handler
 */
app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(500).json({
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : 'An unexpected error occurred'
  });
});

// Initialize database connection
if (USE_DATABASE) {
  console.log('🔄 Initializing database connection...');
  db.initDatabase();
}

// Graceful shutdown handler
const shutdown = (signal) => {
  console.log(`\n${signal} received. Closing database and shutting down gracefully...`);
  if (USE_DATABASE) {
    db.closeDatabase();
  }
  process.exit(0);
};

process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

// Start server
app.listen(PORT, () => {
  console.log(`🚀 IOPHIN API Server running on port ${PORT}`);
  console.log(`📊 Data Mode: ${USE_DATABASE && db.isDatabaseAvailable() ? 'DATABASE (Real-Time)' : 'FILE (Static)'}`);
  console.log(`📊 Data path: ${DATA_PATH}`);
  console.log(`🌍 Environment: ${process.env.NODE_ENV || 'development'}`);
  console.log(`✅ GZIP compression: enabled`);
  console.log(`\n📍 Available endpoints:`);
  console.log(`   - GET http://localhost:${PORT}/api/health`);
  console.log(`   - GET http://localhost:${PORT}/api/hotspots`);
  console.log(`   - GET http://localhost:${PORT}/api/stats`);
  console.log(`   - GET http://localhost:${PORT}/api/lga/:name`);
  
  if (USE_DATABASE && db.isDatabaseAvailable()) {
    console.log(`\n✨ Dynamic Real-Time Mode Active`);
    console.log(`   Data updates automatically from scheduler service`);
  }
});

export default app;
